name: foreground_work_manager
description: "FGWorkManager is a lightweight, easy-to-use foreground job manager for Flutter. Unlike other background job managers, it does not require complex platform-specific configurations. It ensures that jobs are cached and restored even after app restarts, allowing for a seamless job execution process."
version: 0.0.1
homepage: https://github.com/MhdZiadHirati/foreground_work_manager

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  async: ^2.11.0
  flutter:
    sdk: flutter
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:


